apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - configmap-fetch-loop.yaml
  - daemonset.yaml

replacements:
  - source:
      kind: ConfigMap
      name: git-cache-env
      fieldPath: data.GIT_CACHE_SCRIPTS_CONFIG_MAP_NAME
    targets:
      - select:
          kind: ConfigMap
          name: pilotswarm-git-cache-scripts
        fieldPaths:
          - metadata.name
      - select:
          kind: DaemonSet
        fieldPaths:
          - spec.template.spec.volumes.[name=scripts].configMap.name
