import { createTheme } from "./helpers.js";

const nightShiftTheme = createTheme({
    id: "night-shift",
    label: "Night Shift",
    description: "Charcoal and moss dark theme with copper system accents and low-glare sage text.",
    page: {
        background: "#111411",
        foreground: "#d7ddcf",
        overlayBackground: "#171b16",
        overlayForeground: "#e2e8da",
        hintColor: "#9eaa93",
        modalBackdrop: "rgba(8, 10, 8, 0.76)",
        modalBackground: "#1c211a",
        modalBorder: "#4b5a3f",
        modalForeground: "#e2e8da",
        modalMuted: "#9eaa93",
        modalSelectedBackground: "#293622",
        modalSelectedBorder: "#9bbb74",
        modalSelectedForeground: "#f0f5e8",
    },
    terminal: {
        background: "#111411",
        foreground: "#d7ddcf",
        cursor: "#c7d98c",
        cursorAccent: "#111411",
        selectionBackground: "#293622",
        black: "#171b16",
        red: "#e26d5a",
        green: "#8fbc6a",
        yellow: "#c69c5d",
        blue: "#7ba7c9",
        magenta: "#b58bbd",
        cyan: "#7dbda2",
        white: "#d7ddcf",
        brightBlack: "#727b6a",
        brightRed: "#ef8a78",
        brightGreen: "#a6cf80",
        brightYellow: "#d7b375",
        brightBlue: "#92bad7",
        brightMagenta: "#caa4d0",
        brightCyan: "#93d0b6",
        brightWhite: "#eef3e8",
    },
    tui: {
        surface: "#171b16",
        border: "#4b5a3f",
        userChat: "#d7b375",
        userChatLabel: "#edd49b",
        activeHighlightBackground: "#293622",
        activeHighlightForeground: "#f0f5e8",
        selectionBackground: "#9bbb74",
        selectionForeground: "#111411",
        promptCursorBackground: "#c7d98c",
        promptCursorForeground: "#111411",
    },
});

export default nightShiftTheme;