import { createTheme } from "./helpers.js";

const noctisViolaTheme = createTheme({
    id: "noctis-viola",
    label: "Noctis Viola",
    description: "Saturated dark violet palette with purple and warm accents.",
    page: {
        background: "#30243d",
        foreground: "#ccbfd9",
        overlayBackground: "#30243d",
        overlayForeground: "#ccbfd9",
        hintColor: "#bf8ef1",
        modalBackdrop: "rgba(28, 18, 38, 0.72)",
        modalBackground: "#3d2e4d",
        modalBorder: "#8767a8",
        modalForeground: "#ccbfd9",
        modalMuted: "#ad9cc0",
        modalSelectedBackground: "#593a78",
        modalSelectedBorder: "#bf8ef1",
        modalSelectedForeground: "#edebff",
    },
    terminal: {
        background: "#291d35",
        foreground: "#ccbfd9",
        cursor: "#d9b3ff",
        cursorAccent: "#291d35",
        selectionBackground: "rgba(135, 103, 168, 0.33)",
        black: "#362f3d",
        red: "#e66533",
        green: "#49e9a6",
        yellow: "#e4b781",
        blue: "#49ace9",
        magenta: "#df769b",
        cyan: "#49d6e9",
        white: "#bfafcf",
        brightBlack: "#8f869b",
        brightRed: "#e97749",
        brightGreen: "#60ebb1",
        brightYellow: "#e69533",
        brightBlue: "#60b6eb",
        brightMagenta: "#e798b3",
        brightCyan: "#60dbeb",
        brightWhite: "#ccbfd9",
    },
    tui: {
        surface: "#291d35",
        activeHighlightBackground: "#402d53",
        activeHighlightForeground: "#edebff",
        selectionBackground: "#8767a8",
        selectionForeground: "#30243d",
        promptCursorBackground: "#d9b3ff",
        promptCursorForeground: "#291d35",
    },
});

export default noctisViolaTheme;
