import { createTheme } from "./helpers.js";

const paperTrailTheme = createTheme({
    id: "paper-trail",
    label: "Paper Trail",
    description: "Light engineering-notes palette with paper whites, graphite ink, blue-gray actions, and red pencil alerts.",
    page: {
        background: "#f7f8f5",
        foreground: "#23272f",
        overlayBackground: "#ffffff",
        overlayForeground: "#23272f",
        hintColor: "#5d6f82",
        modalBackdrop: "rgba(35, 39, 47, 0.26)",
        modalBackground: "#ffffff",
        modalBorder: "#cdd4d8",
        modalForeground: "#23272f",
        modalMuted: "#64717d",
        modalSelectedBackground: "#e2eef7",
        modalSelectedBorder: "#497ca3",
        modalSelectedForeground: "#17384f",
    },
    terminal: {
        background: "#fbfcf8",
        foreground: "#23272f",
        cursor: "#497ca3",
        cursorAccent: "#ffffff",
        selectionBackground: "#d8e8f2",
        black: "#23272f",
        red: "#b84545",
        green: "#3f7f5f",
        yellow: "#9a6b22",
        blue: "#497ca3",
        magenta: "#7d5d99",
        cyan: "#367f88",
        white: "#e8ebe4",
        brightBlack: "#64717d",
        brightRed: "#9d3131",
        brightGreen: "#2f684b",
        brightYellow: "#825714",
        brightBlue: "#315f83",
        brightMagenta: "#684580",
        brightCyan: "#236973",
        brightWhite: "#23272f",
    },
    tui: {
        surface: "#ffffff",
        border: "#cdd4d8",
        userChat: "#315f83",
        userChatLabel: "#17384f",
        activeHighlightBackground: "#e2eef7",
        activeHighlightForeground: "#17384f",
        selectionBackground: "#497ca3",
        selectionForeground: "#ffffff",
        promptCursorBackground: "#497ca3",
        promptCursorForeground: "#ffffff",
    },
});

export default paperTrailTheme;