import { createTheme } from "./helpers.js";

const solarizedOpsTheme = createTheme({
    id: "solarized-ops",
    label: "Solarized Ops",
    description: "Solarized-inspired operations palette with deep blue-green surfaces and balanced long-session contrast.",
    page: {
        background: "#002b36",
        foreground: "#d7e2d0",
        overlayBackground: "#073642",
        overlayForeground: "#e5efe4",
        hintColor: "#93a1a1",
        modalBackdrop: "rgba(0, 20, 25, 0.74)",
        modalBackground: "#073642",
        modalBorder: "#2f5d67",
        modalForeground: "#e5efe4",
        modalMuted: "#93a1a1",
        modalSelectedBackground: "#164b56",
        modalSelectedBorder: "#2aa198",
        modalSelectedForeground: "#fdf6e3",
    },
    terminal: {
        background: "#002b36",
        foreground: "#d7e2d0",
        cursor: "#2aa198",
        cursorAccent: "#002b36",
        selectionBackground: "#164b56",
        black: "#073642",
        red: "#dc322f",
        green: "#859900",
        yellow: "#b58900",
        blue: "#268bd2",
        magenta: "#6c71c4",
        cyan: "#2aa198",
        white: "#eee8d5",
        brightBlack: "#586e75",
        brightRed: "#cb4b16",
        brightGreen: "#93a100",
        brightYellow: "#c79b00",
        brightBlue: "#3aa0e6",
        brightMagenta: "#7b80d6",
        brightCyan: "#36b5ac",
        brightWhite: "#fdf6e3",
    },
    tui: {
        surface: "#073642",
        border: "#2f5d67",
        userChat: "#b58900",
        userChatLabel: "#f0d47a",
        activeHighlightBackground: "#164b56",
        activeHighlightForeground: "#fdf6e3",
        selectionBackground: "#268bd2",
        selectionForeground: "#002b36",
        promptCursorBackground: "#2aa198",
        promptCursorForeground: "#002b36",
    },
});

export default solarizedOpsTheme;