import { createTheme } from "./helpers.js";

const workbenchLightTheme = createTheme({
    id: "workbench-light",
    label: "Workbench Light",
    description: "Quiet daytime workbench theme with cool gray surfaces, white panels, and blue operational accents.",
    page: {
        background: "#eef2f5",
        foreground: "#1f2933",
        overlayBackground: "#ffffff",
        overlayForeground: "#1f2933",
        hintColor: "#64748b",
        modalBackdrop: "rgba(31, 41, 51, 0.28)",
        modalBackground: "#ffffff",
        modalBorder: "#cbd5df",
        modalForeground: "#1f2933",
        modalMuted: "#667788",
        modalSelectedBackground: "#dbeafe",
        modalSelectedBorder: "#2563eb",
        modalSelectedForeground: "#1e3a8a",
    },
    terminal: {
        background: "#f8fafc",
        foreground: "#1f2933",
        cursor: "#2563eb",
        cursorAccent: "#ffffff",
        selectionBackground: "#dbeafe",
        black: "#1f2933",
        red: "#c2413c",
        green: "#15803d",
        yellow: "#a16207",
        blue: "#2563eb",
        magenta: "#7c3aed",
        cyan: "#0f766e",
        white: "#e5e9ef",
        brightBlack: "#64748b",
        brightRed: "#a8322e",
        brightGreen: "#166534",
        brightYellow: "#854d0e",
        brightBlue: "#1d4ed8",
        brightMagenta: "#6d28d9",
        brightCyan: "#0f5f59",
        brightWhite: "#1f2933",
    },
    tui: {
        surface: "#ffffff",
        border: "#cbd5df",
        userChat: "#1d4ed8",
        userChatLabel: "#1e3a8a",
        activeHighlightBackground: "#dbeafe",
        activeHighlightForeground: "#1e3a8a",
        selectionBackground: "#2563eb",
        selectionForeground: "#ffffff",
        promptCursorBackground: "#2563eb",
        promptCursorForeground: "#ffffff",
    },
});

export default workbenchLightTheme;