# GenerateEnvForEv2.ps1 — PilotSwarm EV2 shell extension
#
# Writes a <OverlayPath>/.env file populated from EV2 scope-binding
# environment variables. Consumed by the Kustomize overlay's
# configMapGenerator (the overlay's .env is re-generated at rollout time
# so that the rendered manifest contains fully-resolved values before
# DeployApplicationManifest.sh publishes it to blob storage).
#
# Contract:
#   - Only non-empty env vars are written.
#   - The file is overwritten in place; a warning header identifies it as
#     auto-generated.
#   - The list of recognized variables is intentionally extensible — add
#     new keys to the $RecognizedVars array below.
#
# Usage:
#   pwsh -NoProfile -File GenerateEnvForEv2.ps1 -OverlayPath <path>

[CmdletBinding()]
param (
    [Parameter(Mandatory = $true)]
    [string]$OverlayPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if (-not (Test-Path -LiteralPath $OverlayPath -PathType Container)) {
    throw "Overlay path does not exist or is not a directory: $OverlayPath"
}

# Extensible list of env vars this script will copy into .env.
# Keep in sync with Kustomize overlay configMapGenerator expectations and
# with the EV2 rollout `environmentVariables` block.
$RecognizedVars = @(
    'IMAGE_TAG',
    'IMAGE_NAME',
    'ACR_LOGIN_SERVER',
    'NAMESPACE',
    'WORKLOAD_IDENTITY_CLIENT_ID',
    'PORTAL_HOSTNAME',
    'KV_NAME',
    'AZURE_TENANT_ID',
    'AZURE_CLIENT_ID'
)

$envFilePath = Join-Path -Path $OverlayPath -ChildPath '.env'
Write-Host "Generating env file: $envFilePath"

$lines = @(
    '# AUTO-GENERATED by GenerateEnvForEv2.ps1 — do not edit by hand.',
    '# Values are sourced from EV2 scope-binding environment variables at rollout time.'
)

foreach ($name in $RecognizedVars) {
    $value = [Environment]::GetEnvironmentVariable($name)
    if (-not [string]::IsNullOrEmpty($value)) {
        Write-Host "  $name=$value"
        $lines += "$name=$value"
    }
    else {
        Write-Host "  (skipping $name — not set)"
    }
}

$lines | Set-Content -Path $envFilePath -Encoding UTF8
Write-Host "Wrote $($lines.Count) lines to $envFilePath"
