// @generated by packages/sdk/scripts/generate-web-client-ops.mjs — DO NOT EDIT.
// Regenerate: npm run generate:web-ops -w packages/sdk
//
// One method per entry in the protocol table (packages/sdk/api/src/protocol.js),
// so the web management client cannot drift from the operations the Web API
// actually exposes. See contract test: web-client-op-coverage.

/** Every operation name in the protocol table, sorted. */
export const GENERATED_OP_NAMES: readonly string[] = [
    "assignSessionsToGroup",
    "cancelPendingMessage",
    "cancelSession",
    "cancelSessionGroup",
    "completeSession",
    "completeSessionGroup",
    "createSession",
    "createSessionForAgent",
    "createSessionGroup",
    "deleteAgentPackage",
    "deleteArtifact",
    "deleteFact",
    "deleteGraphEdge",
    "deleteGraphNamespace",
    "deleteGraphNode",
    "deleteSession",
    "deleteSessionGroup",
    "downloadArtifact",
    "exportExecutionHistory",
    "factsCapabilities",
    "forcePurgeFacts",
    "getAgentPackage",
    "getAgentPackageFile",
    "getAgentPackageTree",
    "getArtifactMetadata",
    "getChildOutcome",
    "getCurrentUserProfile",
    "getDefaultModel",
    "getEmbedderStatus",
    "getExecutionHistory",
    "getFactsTombstoneStats",
    "getFleetGraphNodeUsage",
    "getFleetRetrievalUsage",
    "getFleetSkillUsage",
    "getFleetStats",
    "getGraphNamespace",
    "getLatestResponse",
    "getLogConfig",
    "getModelsByProvider",
    "getOrchestrationStats",
    "getSession",
    "getSessionAccess",
    "getSessionCreationPolicy",
    "getSessionEvents",
    "getSessionEventsBefore",
    "getSessionFactsStats",
    "getSessionFootprint",
    "getSessionGraphEdgeSearchUsage",
    "getSessionGraphNodeUsage",
    "getSessionGraphSearches",
    "getSessionMetricSummary",
    "getSessionRetrievalUsage",
    "getSessionSkillUsage",
    "getSessionStatus",
    "getSessionTokensByModel",
    "getSessionTreeFactsStats",
    "getSessionTreeRetrievalUsage",
    "getSessionTreeSkillUsage",
    "getSessionTreeStats",
    "getSharedFactsStats",
    "getSystemGitHubCopilotKeyStatus",
    "getTopEventEmitters",
    "getUserStats",
    "getWorkerCount",
    "grantSessionShare",
    "graphNeighbourhood",
    "graphStats",
    "listAgentPackages",
    "listAgentWorkerState",
    "listArtifacts",
    "listAuthzAudit",
    "listChildOutcomes",
    "listCreatableAgents",
    "listGraphNamespaces",
    "listKnownUsers",
    "listModels",
    "listSessionGroups",
    "listSessions",
    "listSessionShares",
    "listSessionsPage",
    "listWorkers",
    "moveSessionsToGroup",
    "pinAgentPackageVersion",
    "placeSessionsInGroup",
    "pruneDeletedSummaries",
    "readFacts",
    "regenerateSession",
    "renameSession",
    "restartSystemSession",
    "revokeSessionShare",
    "searchFacts",
    "searchGraphEdges",
    "searchGraphNodes",
    "sendAnswer",
    "sendMessage",
    "sendSessionEvent",
    "setAgentPackageEnabled",
    "setAgentPackageScope",
    "setCurrentUserGitHubCopilotKey",
    "setCurrentUserProfileSettings",
    "setSessionModel",
    "setSessionVisibility",
    "setSystemGitHubCopilotKey",
    "similarFacts",
    "startFactsEmbedder",
    "stopFactsEmbedder",
    "stopSessionTurn",
    "storeFact",
    "updateSessionGroup",
    "uploadAgentPackage",
    "uploadArtifact",
    "upsertGraphEdge",
    "upsertGraphNamespace",
    "upsertGraphNode",
    "waitForStatusChange",
];

/**
 * Operations the client implements by hand, with ergonomic (non-flat)
 * signatures. These are omitted from `GeneratedOpMethods` and skipped by the
 * runtime install — they are covered, not missing.
 */
export const HAND_WRITTEN_OP_NAMES: readonly string[] = [
    "assignSessionsToGroup",
    "cancelPendingMessage",
    "cancelSession",
    "cancelSessionGroup",
    "completeSession",
    "completeSessionGroup",
    "createSessionGroup",
    "deleteSession",
    "deleteSessionGroup",
    "getChildOutcome",
    "getDefaultModel",
    "getEmbedderStatus",
    "getExecutionHistory",
    "getFactsTombstoneStats",
    "getFleetGraphNodeUsage",
    "getFleetRetrievalUsage",
    "getFleetSkillUsage",
    "getFleetStats",
    "getLatestResponse",
    "getModelsByProvider",
    "getOrchestrationStats",
    "getSession",
    "getSessionEvents",
    "getSessionEventsBefore",
    "getSessionFactsStats",
    "getSessionFootprint",
    "getSessionGraphEdgeSearchUsage",
    "getSessionGraphNodeUsage",
    "getSessionGraphSearches",
    "getSessionMetricSummary",
    "getSessionRetrievalUsage",
    "getSessionSkillUsage",
    "getSessionStatus",
    "getSessionTokensByModel",
    "getSessionTreeFactsStats",
    "getSessionTreeRetrievalUsage",
    "getSessionTreeSkillUsage",
    "getSessionTreeStats",
    "getSharedFactsStats",
    "getSystemGitHubCopilotKeyStatus",
    "getTopEventEmitters",
    "getUserStats",
    "listChildOutcomes",
    "listModels",
    "listSessionGroups",
    "listSessions",
    "listSessionsPage",
    "moveSessionsToGroup",
    "placeSessionsInGroup",
    "pruneDeletedSummaries",
    "regenerateSession",
    "renameSession",
    "restartSystemSession",
    "sendAnswer",
    "sendMessage",
    "setSessionModel",
    "setSystemGitHubCopilotKey",
    "stopSessionTurn",
    "updateSessionGroup",
    "waitForStatusChange",
];

/**
 * Operation methods installed onto the web management client. Each takes the
 * operation's params as a single flat object and resolves the JSON result.
 *
 * Declaration-merged into `WebPilotSwarmManagementClient`. Only operations the
 * class does not already implement appear here.
 */
export interface GeneratedOpMethods {
    /**
     * Create a session. Owner is the authenticated principal; visibility defaults to the deployment default.
     * @remarks `POST /sessions` — access: `session:create`
     */
    createSession(params: {
        model?: any;
        reasoningEffort?: any;
        contextTier?: any;
        groupId?: any;
        visibility?: any;
    }): Promise<any>;

    /**
     * Create a session bound to a named agent.
     * @remarks `POST /sessions/for-agent` — access: `session:create`
     */
    createSessionForAgent(params: {
        agentName?: any;
        model?: any;
        reasoningEffort?: any;
        contextTier?: any;
        title?: any;
        splash?: any;
        splashMobile?: any;
        initialPrompt?: any;
        groupId?: any;
        visibility?: any;
    }): Promise<any>;

    /**
     * Delete a package: every version and its artifacts. Creator or admin. Live sessions using its agents fail resolution on their next turn.
     * @remarks `DELETE /agent-packages/:name` — access: `authed`
     */
    deleteAgentPackage(params: {
        name: string;
    }): Promise<any>;

    /**
     * Delete an artifact.
     * @remarks `DELETE /sessions/:sessionId/artifacts/:filename` — access: `session:manage`
     */
    deleteArtifact(params: {
        sessionId: string;
        filename: string;
    }): Promise<any>;

    /**
     * Delete a fact / pattern (DeleteFactInput). POST because DELETE bodies are unreliable.
     * @remarks `POST /facts/delete` — access: `facts:write`
     */
    deleteFact(params: {
        input?: any;
    }): Promise<any>;

    /**
     * Delete a graph edge.
     * @remarks `POST /graph/edges/delete` — access: `authed`
     */
    deleteGraphEdge(params: {
        fromKey?: any;
        toKey?: any;
        predicateKey?: any;
        namespace?: any;
    }): Promise<any>;

    /**
     * Delete a graph namespace and its data. [admin]
     * @remarks `DELETE /graph/namespaces/:namespace` — access: `fleet:admin` (admin)
     */
    deleteGraphNamespace(params: {
        namespace: string;
    }): Promise<any>;

    /**
     * Delete a graph node.
     * @remarks `POST /graph/nodes/delete` — access: `authed`
     */
    deleteGraphNode(params: {
        nodeKey?: any;
        namespace?: any;
    }): Promise<any>;

    /**
     * Artifact content as text (JSON envelope). Binary: GET …/download.
     * @remarks `GET /sessions/:sessionId/artifacts/:filename/text` — access: `session:read`
     */
    downloadArtifact(params: {
        sessionId: string;
        filename: string;
    }): Promise<any>;

    /**
     * Export execution history to an artifact; returns artifact meta.
     * @remarks `POST /management/sessions/:sessionId/export-execution-history` — access: `session:manage`
     */
    exportExecutionHistory(params: {
        sessionId: string;
    }): Promise<any>;

    /**
     * Store capabilities: { search, embedder, graph } — the remote isEnhancedFactStore/isGraphStore.
     * @remarks `GET /facts/capabilities` — access: `authed`
     */
    factsCapabilities(params?: Record<string, never>): Promise<any>;

    /**
     * Force-purge soft-deleted facts (ForcePurgeFactsInput). [admin]
     * @remarks `POST /facts/purge` — access: `fleet:admin` (admin)
     */
    forcePurgeFacts(params: {
        input?: any;
    }): Promise<any>;

    /**
     * One package with its full version history.
     * @remarks `GET /agent-packages/:name` — access: `authed`
     */
    getAgentPackage(params: {
        name: string;
    }): Promise<any>;

    /**
     * One file from the package tarball (preview; text size-capped, binary flagged).
     * @remarks `GET /agent-packages/:name/file` — access: `authed`
     */
    getAgentPackageFile(params: {
        name: string;
        semver?: string;
        filePath?: string;
    }): Promise<any>;

    /**
     * File tree of the package tarball (workspace viewer). Defaults to the active version.
     * @remarks `GET /agent-packages/:name/tree` — access: `authed`
     */
    getAgentPackageTree(params: {
        name: string;
        semver?: string;
    }): Promise<any>;

    /**
     * Artifact metadata.
     * @remarks `GET /sessions/:sessionId/artifacts/:filename/meta` — access: `session:read`
     */
    getArtifactMetadata(params: {
        sessionId: string;
        filename: string;
    }): Promise<any>;

    /**
     * Profile of the authenticated principal.
     * @remarks `GET /me/profile` — access: `authed`
     */
    getCurrentUserProfile(params?: Record<string, never>): Promise<any>;

    /**
     * One graph namespace descriptor.
     * @remarks `GET /graph/namespaces/:namespace` — access: `authed`
     */
    getGraphNamespace(params: {
        namespace: string;
    }): Promise<any>;

    /**
     * Log tail availability.
     * @remarks `GET /system/log-config` — access: `authed`
     */
    getLogConfig(params?: Record<string, never>): Promise<any>;

    /**
     * The caller's effective access to this session's tree: { visibility, relation, canWrite, canManage, owner }.
     * @remarks `GET /sessions/:sessionId/access` — access: `session:read`
     */
    getSessionAccess(params: {
        sessionId: string;
    }): Promise<any>;

    /**
     * Session creation policy.
     * @remarks `GET /session-creation-policy` — access: `authed`
     */
    getSessionCreationPolicy(params?: Record<string, never>): Promise<any>;

    /**
     * Live worker count.
     * @remarks `GET /system/workers` — access: `authed`
     */
    getWorkerCount(params?: Record<string, never>): Promise<any>;

    /**
     * Grant (or update) a targeted share ({ user: { provider, subject, email?, displayName? }, access: read|write }). Owner or admin.
     * @remarks `POST /sessions/:sessionId/shares` — access: `session:share`
     */
    grantSessionShare(params: {
        sessionId: string;
        user?: any;
        access?: any;
    }): Promise<any>;

    /**
     * Expand a subgraph around a node.
     * @remarks `POST /graph/neighbourhood` — access: `authed`
     */
    graphNeighbourhood(params: {
        nodeKey?: any;
        depth?: any;
        namespace?: any;
    }): Promise<any>;

    /**
     * Graph node/edge counts.
     * @remarks `GET /graph/stats` — access: `authed`
     */
    graphStats(params: {
        namespace?: string;
    }): Promise<any>;

    /**
     * Agent packages visible to the caller: shared + own user-scope (admins see all).
     * @remarks `GET /agent-packages` — access: `authed`
     */
    listAgentPackages(params?: Record<string, never>): Promise<any>;

    /**
     * Per-worker installed package state (fleet adoption). Hard admin gate: the installed map enumerates every package name, including user-scope ones. [admin]
     * @remarks `GET /agent-packages/worker-state` — access: `fleet:admin` (admin)
     */
    listAgentWorkerState(params?: Record<string, never>): Promise<any>;

    /**
     * List artifacts for a session.
     * @remarks `GET /sessions/:sessionId/artifacts` — access: `session:read`
     */
    listArtifacts(params: {
        sessionId: string;
    }): Promise<any>;

    /**
     * Authz audit records, newest first. Admin fleet-wide; owners for their own sessions (sessionId required).
     * @remarks `GET /management/authz-audit` — access: `authz:audit`
     */
    listAuthzAudit(params: {
        limit?: number;
        sessionId?: string;
    }): Promise<any>;

    /**
     * Agents sessions can be created for.
     * @remarks `GET /agents` — access: `authed`
     */
    listCreatableAgents(params?: Record<string, never>): Promise<any>;

    /**
     * List graph namespaces (corpora).
     * @remarks `GET /graph/namespaces` — access: `authed`
     */
    listGraphNamespaces(params: {
        prefix?: string;
        includeArchived?: boolean;
        includeDetails?: boolean;
    }): Promise<any>;

    /**
     * Member directory (provider/subject/email/displayName) for share autocomplete; excludes synthetic principals.
     * @remarks `GET /management/users` — access: `authed`
     */
    listKnownUsers(params: {
        limit?: number;
    }): Promise<any>;

    /**
     * List targeted shares on this session's tree. Owner or admin.
     * @remarks `GET /sessions/:sessionId/shares` — access: `session:share`
     */
    listSessionShares(params: {
        sessionId: string;
    }): Promise<any>;

    /**
     * Worker registry (0040): every registered worker with pool, lifecycle phase, liveness, write-once info, health snapshot, and per-domain state. Hard admin gate. [admin]
     * @remarks `GET /workers` — access: `fleet:admin` (admin)
     */
    listWorkers(params?: Record<string, never>): Promise<any>;

    /**
     * Pin the active version (rollback). Creator or admin; fleet converges on the next epoch poll.
     * @remarks `PUT /agent-packages/:name/active` — access: `authed`
     */
    pinAgentPackageVersion(params: {
        name: string;
        semver?: any;
    }): Promise<any>;

    /**
     * Read facts (ReadFactsQuery params).
     * @remarks `GET /facts` — access: `facts:read`
     */
    readFacts(params: {
        keyPattern?: string;
        scopeKeys?: any;
        tags?: any;
        sessionId?: string;
        agentId?: string;
        limit?: number;
        scope?: string;
    }): Promise<any>;

    /**
     * Revoke a targeted share ({ user: { provider, subject } }). Owner or admin.
     * @remarks `POST /sessions/:sessionId/shares/revoke` — access: `session:share`
     */
    revokeSessionShare(params: {
        sessionId: string;
        user?: any;
    }): Promise<any>;

    /**
     * Retrieval over facts (lexical | semantic | hybrid). [enhanced]
     * @remarks `POST /facts/search` — access: `facts:read`
     */
    searchFacts(params: {
        query?: any;
        opts?: any;
    }): Promise<any>;

    /**
     * Search graph edges (GraphEdgeQuery).
     * @remarks `POST /graph/edges/search` — access: `authed`
     */
    searchGraphEdges(params: {
        query?: any;
    }): Promise<any>;

    /**
     * Search graph nodes (GraphNodeQuery).
     * @remarks `POST /graph/nodes/search` — access: `authed`
     */
    searchGraphNodes(params: {
        query?: any;
    }): Promise<any>;

    /**
     * Send a custom event into the session.
     * @remarks `POST /sessions/:sessionId/events` — access: `session:write`
     */
    sendSessionEvent(params: {
        sessionId: string;
        eventName?: any;
        data?: any;
    }): Promise<any>;

    /**
     * Enable/disable a package fleet-wide. Creator or admin.
     * @remarks `PUT /agent-packages/:name/enabled` — access: `authed`
     */
    setAgentPackageEnabled(params: {
        name: string;
        enabled?: any;
    }): Promise<any>;

    /**
     * Promote (shared) or demote (user). Creator or admin; running agents unaffected.
     * @remarks `PUT /agent-packages/:name/scope` — access: `authed`
     */
    setAgentPackageScope(params: {
        name: string;
        scope?: any;
    }): Promise<any>;

    /**
     * Set (or clear with null) the per-user GitHub Copilot key.
     * @remarks `PUT /me/github-copilot-key` — access: `authed`
     */
    setCurrentUserGitHubCopilotKey(params: {
        key?: any;
    }): Promise<any>;

    /**
     * Replace profile settings.
     * @remarks `PATCH /me/profile/settings` — access: `authed`
     */
    setCurrentUserProfileSettings(params: {
        settings?: any;
    }): Promise<any>;

    /**
     * Set the tree's sharing level (private | shared_read | shared_write). Owner or admin.
     * @remarks `PUT /sessions/:sessionId/visibility` — access: `session:share`
     */
    setSessionVisibility(params: {
        sessionId: string;
        visibility?: any;
    }): Promise<any>;

    /**
     * Semantic nearest-neighbours of a known fact. [enhanced]
     * @remarks `POST /facts/similar` — access: `facts:read`
     */
    similarFacts(params: {
        scopeKey?: any;
        opts?: any;
    }): Promise<any>;

    /**
     * Start the durable embedder loop. [enhanced, admin]
     * @remarks `POST /facts/embedder/start` — access: `fleet:admin` (admin)
     */
    startFactsEmbedder(params: {
        intervalSeconds?: any;
        batch?: any;
    }): Promise<any>;

    /**
     * Stop the durable embedder loop. [enhanced, admin]
     * @remarks `POST /facts/embedder/stop` — access: `fleet:admin` (admin)
     */
    stopFactsEmbedder(params: {
        reason?: any;
    }): Promise<any>;

    /**
     * Store a fact or facts (StoreFactInput | StoreFactInput[]).
     * @remarks `POST /facts` — access: `facts:write`
     */
    storeFact(params: {
        input?: any;
    }): Promise<any>;

    /**
     * Publish a package from inline files ([{path, contentBase64}], ≤ 2 MB total); validates, canonically packs, and registers as the caller.
     * @remarks `POST /agent-packages/upload` — access: `authed`
     */
    uploadAgentPackage(params: {
        files?: any;
        scope?: any;
    }): Promise<any>;

    /**
     * Upload artifact content (base64 for binary; 2 MB JSON limit).
     * @remarks `PUT /sessions/:sessionId/artifacts/:filename` — access: `session:write`
     */
    uploadArtifact(params: {
        sessionId: string;
        filename: string;
        content?: any;
        contentType?: any;
        contentEncoding?: any;
    }): Promise<any>;

    /**
     * Upsert a graph edge (GraphEdgeInput).
     * @remarks `POST /graph/edges` — access: `authed`
     */
    upsertGraphEdge(params: {
        input?: any;
    }): Promise<any>;

    /**
     * Register/update a graph namespace. [admin]
     * @remarks `POST /graph/namespaces` — access: `fleet:admin` (admin)
     */
    upsertGraphNamespace(params: {
        input?: any;
    }): Promise<any>;

    /**
     * Upsert a graph node (GraphNodeInput).
     * @remarks `POST /graph/nodes` — access: `authed`
     */
    upsertGraphNode(params: {
        input?: any;
    }): Promise<any>;
}

/**
 * Install a method per operation onto `proto`, skipping any name the class
 * already defines. Hand-written methods win — that is what keeps existing
 * ergonomic signatures (and their callers) working.
 *
 * @param proto prototype to install onto
 * @param callOp `(self, name, params) => Promise<any>` invoked by each method
 * @returns the operation names actually installed
 */
export function installGeneratedOpMethods(
    proto: object,
    callOp: (self: any, name: string, params: Record<string, unknown>) => Promise<any>,
): string[] {
    const installed: string[] = [];
    for (const name of GENERATED_OP_NAMES) {
        if (Object.prototype.hasOwnProperty.call(proto, name)) continue;
        Object.defineProperty(proto, name, {
            value: function (params: Record<string, unknown> = {}) {
                return callOp(this, name, params);
            },
            writable: true,
            configurable: true,
            enumerable: false,
        });
        installed.push(name);
    }
    return installed;
}
